### ISSUE TITLE
Check multiple providers

### ISSUE THREAD

**Issue by twiz911** [nbulaj/proxy_fetcher#6]
Is it possible to check multiple providers e.g.

```
    ProxyFetcher.configure do |config|
      config.provider = [:free_proxy_list, :free_proxy_list_ssl, ...]
    end
```

Thanks

**Comment by nbulaj** [comment]
@twiz911currently no, but I wat thinking about it just a few days ago. I think I will implement it for a next release.

**Comment by twiz911** [comment]
Many thanks for the quick turnaround. How do I enable multiple providers at the same time?

**Comment by nbulaj** [comment]
@twiz911 you need to use `multiple_providers` branch (at now):

```ruby
gem 'proxy_fetcher', git: 'https://github.com/nbulaj/proxy_fetcher.git', branch: 'multiple_providers'
```

And set providers as usual, but now it can be an array of names:

```ruby
ProxyFetcher.config.providers = [:hide_my_name, :proxy_docker, :xroxy]
```

Or you can use all the registered providers:

```ruby
ProxyFetcher.config.providers = ProxyFetcher::Configuration.registered_providers
```

And then just:

```ruby
proxies = ProxyFetcher::Manager.new.proxies
```

**Comment by twiz911** [comment]
Many thanks.

I had to add 

`def refresh_list!(filters = {})`

in manager.rb to avoid a nil.any? in load_document

**Comment by twiz911** [comment]
Although the new version seems really slow to discover proxies? I'd expect it to be faster if it can check all providers at the same time?

Thanks

**Comment by nbulaj** [comment]
@twiz911 [no need to](https://github.com/nbulaj/proxy_fetcher/blob/multiple_providers/lib/proxy_fetcher/providers/base.rb#L26). Just make `bundle install` :)

What about the speed - [check the docs](https://github.com/nbulaj/proxy_fetcher/tree/multiple_providers#in-ruby-application), section that starts with _"In order to increase the speed "_.

In a few words, ProxyFetcher gem uses threads to validate proxies for availability, and you can pass a number of max thread pool to `validate!` (or `cleanup!`) method: `manager.cleanup!(50)`. You can experiment with it to find an optimal number of max threads count for you PC and OS. This will give you some performance improvements (for example I increased this number from 10 to 50 for my old laptop and validation time decreased from 140 seconds to only 40).

Moreover, the common proxy validation speed depends on `ProxyFetcher.config.connection_timeout`, that equal to 3 by default. It means that gem will wait 3 seconds for the server answer to check if particular proxy is connectable. You can decrease this option to `1`, for example, and it will heavily increase proxy validation speed (**but remember** that some proxies could be connectable, but slow, so with this option you will clear proxy list from the proxies that works, but very slow).

**Comment by nbulaj** [comment]
@twiz911 released with [0.4.0](https://rubygems.org/gems/proxy_fetcher/versions/0.4.0). Check out the docs or my advice above for increasing proxy validation speed.

**Comment by twiz911** [comment]
Many thanks I have pulled the latest release and it all works as expected :+1:

**Comment by twiz911** [comment]
(Although I noticed validate method no longer takes an input but the Readme still says it does).

**Comment by nbulaj** [comment]
@twiz911 yeap, forgot about this section. Thanks!
